### PR TITLE
Added MARIADB_AUTO_UPGRADE=1

### PR DESCRIPTION
**Pull request by d7oc**
Fixes: #1044

Backport to 10.11 and 10.12

### CODE REVIEW

**Comment by mmattel** [comment]
According to: `MariaDB/mariadb-docker/issues/350`, you need to run
`mysql_upgrade` or `mariadb-upgrade` as part of the upgrade procedure when using a bare metal environment. `MARIADB_AUTO_UPGRADE` is the docker version of it and for MariaDB only.

To have a more neutral approach, see: [Upgrading Databases in Docker](https://theorangeone.net/posts/upgrading-docker-databases/). This would be inline for both bare-metal and docker as it uses the same underlaying command.

**Comment by d7oc** [comment]
IMHO this is contradictory to the container approach if you start executing arbitrary commands in containers. Thus the correct way would be the ENV setting for docker.

**Comment by mmattel** [comment]
> Thus the correct way would be the ENV setting for docker.

Fully agreed. What is the envvar for mysql (if one exists, I have not found one)?
We can use the envvar for MariaDB and use the docker command showing an alternative for mysql. AND adding the plain command to the bare-metal environment.
No-go: MariaDB only, no bare-metal.
Comments and ideas welcomed.

**Comment by d7oc** [comment]
> Fully agreed. What is the envvar for mysql (if one exists, I have not found one)?

Seems for MySQL this isn't required according to this article: https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-getting-started.html#docker-upgrading

So it will just automatically update the database without having a special ENV var set.

**Comment by mmattel** [comment]
> Seems for MySQL this isn't required according to this article:

reading the note in the article just a bit below:
...
For MySQL 8.0.15 and earlier: You need to complete the upgrade process by running the [mysql_upgrade](https://dev.mysql.com/doc/refman/8.0/en/mysql-upgrade.html) utility in the MySQL 8.0 Server container (the step is not required for MySQL 8.0.16 and later):
...

**Comment by d7oc** [comment]
I missed that, but given the support status: https://endoflife.date/mysql I would add just a disclaimer that users should use 8.0.16 or later instead of describing this.

Side note: If you set the 8.0 tag in MySQL you will get 8.0.34 right now anyway: https://hub.docker.com/layers/library/mysql/8.0/images/sha256-1da5cf22e7177925fa4d2a707936ca4ade59ba10b40b23550b0ffc12f8340600?context=explore

So I'm not sure if that needs to be written at all. As you explicitly need to pin an old version to run into this.

**Review by mmattel — APPROVED** [review]

**Pull request merged**
