### PR TITLE
[master] ui-testing.adoc - deprecate mailhog in favor of inbucket

### LINKED ISSUE #924: modules/developer_manual/pages/testing/ui-testing.adoc still mentions mailhog
## WHAT Needs to be Documented?
mailhog is no longer used for testing, we now use inbucket.

## WHERE Does This Need To Be Documented (Link)?
modules/developer_manual/pages/testing/ui-testing.adoc

## WHY Should This Change Be Made?
Acceptance tests cannot succeed, when the setup is done according to the  documentation:
```
   ...
    And the administrator clicks on send test email in the admin general settings page using the webUI # WebUIAdminGeneralSettingsContext::theAdministratorClicksOnSendTestEmailInTheAdminGeneralSettingsPageUsingTheWebui()
    Then the email address "admin@owncloud.com" should have received an email with the body containing # EmailContext::emailAddressShouldHaveReceivedAnEmailWithBodyContaining()
      """
      If you received this email, the settings seem to be correct.
      """
      cURL error 7: Failed to connect to 127.0.0.1 port 9000: Connection refused
```

Docu does not mention port 9000.
Instead we say ```docker run -p 1025:1025 -p 8025:8025 mailhog/mailhog``` 
Cannot work. Different ports, and possibly also different protocol.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

### PR DESCRIPTION
**Pull request by phil-davis**
forward-port #925 to master branch

fixes #924

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
do we need an backports like 10.12 / 10.11?

**Comment by jnweiger** [comment]
Developer documentation for 10.11 is not needed, If you ask me.

Am 9. April 2023 08:28:18 MESZ schrieb Martin ***@***.***>:
>do we need an backports like 10.12 / 10.11?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/docs-server/pull/926#issuecomment-1501053331
>You are receiving this because your review was requested.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Review by jnweiger — APPROVED** [review]
Forward port yes!

**Comment by jnweiger** [comment]
The same doc also mentions

```
bash tests/travis/start_php_dev_server.sh
```
Probably also outdated? Haven't heard  about travis for quite a while, and could not find this script.

**Comment by phil-davis** [comment]
The original PR was to 10.12 branch. This PR is to master - that should be enough.

**Comment by phil-davis** [comment]
> Travis - Probably also outdated?

Definitely. I raised issue #927 and will double-check all the test-running docs for that and any other out-of-date crud.

**Pull request merged**
