### PR TITLE
Minor edits to README.md

### PR DESCRIPTION
**Pull request by phil-davis**
Doing this to see what is happening with drone CI.

### CODE REVIEW

**Comment by phil-davis** [comment]
"nothing happens" (tm) on drone.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/docs-server

@mmattel drone does not start at all. I do not have privs to see or edit the settings in drone, or of this GitHub repo. So I can't see what might be the problem. Maybe something was changed recently?

**Comment by phil-davis** [comment]
The drone CI problem has been fixed. I rebased.

**Review by mmattel — APPROVED** [review]
👍

**Comment by phil-davis** [comment]
No need to back-port.

**Pull request merged**
