### PR TITLE
config apps sample update (openidconnect)

### PR DESCRIPTION
**Pull request by mmattel**
Update of the config.sample file

Fixes: https://github.com/owncloud/docs-server/issues/514 (openidconnect: Account info auto-update)

ATM no backport, as this is for 10.11, if required we can backport to 10.10 / 10.9

@jnweiger fyi

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
I expect that the related openidconnect release will be tested against a core 10.10 system (and maybe also against core 10.9?)
If so, then the docs should be backported - @jnweiger  ?

**Comment by jnweiger** [comment]
> I expect that the related openidconnect release will be tested against a core 10.10 system (and maybe also against core 10.9?) If so, then the docs should be backported - @jnweiger ?

o.k. will test against the old versions too.

**Comment by mmattel** [comment]
@jnweiger have you done the tests and can we merge/backport?
Just want to get that off the table...

**Comment by jnweiger** [comment]
PR was merged today. I'll build the release candidate now, then QA can start (slowly). As I said, including 10.10 and 10.9

**Pull request merged**
