### PR TITLE
Update certificates.adoc

### PR DESCRIPTION
**Pull request by rezman42**
ucr seems not to be available

### CODE REVIEW

**Comment by mmattel** [comment]
@d7oc can you double check?

**Comment by d7oc** [comment]
First of all: Which UCS version are we talking about? I don't have one installation at hand but according to their documentation even UCS 5 still has ucr: https://docs.software-univention.de/manual/5.0/en/ip-config/radius.html?highlight=ucr#service-specific-password

**Comment by d7oc** [comment]
ucr is a command in UCS. Don't know why you are talking about Ubuntu here.

**Comment by rezman42** [comment]
thank you for clarifying, i got this wrong -> withdrawing/ closing the PR

**Pull request closed without merging**
