### PR TITLE
Update impersonate_users.adoc

### PR DESCRIPTION
**Pull request by jnweiger**
Never logged in -> no impersonate!

But are we sure, that impersonate is incompatible with shibboleth or openidconnect? I never noticed that...

### CODE REVIEW

**Comment by cdamken** [comment]
@jnweiger I don't want to be a smart-ass, but IMHO the word `before` is not needed 
```
Impersonating is not possible when the specific user has never logged in.
```

**Comment by jnweiger** [comment]
That is fine with me either way. My idea was, that redundant language could server as an emphasis.

A language reviewer might also wonder, why we have a gerund in "Impersonating is not possible ..."
"Impersonate is not possible ..." should work the same. IMO.

**Comment by cdamken** [comment]
> But are we sure, that impersonate is incompatible with shibboleth or openidconnect? I never noticed that...

how about this part?

**Comment by jnweiger** [comment]
> > But are we sure, that impersonate is incompatible with shibboleth or openidconnect? I never noticed that...
> 
> how about this part?

At least openid works fine, IMO -> https://github.com/owncloud/docs-server/pull/1038

**Review by mmattel — APPROVED** [review]

**Pull request merged**
