### PR TITLE
[10.15] [PR 1357] Antora package.json refactoring

### PR DESCRIPTION
**Pull request by mmattel**
Backport of PR #1357

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/docs-server/2953/2/4
```
+ yarn antora --attribute format=html
yarn run v1.22.22
$ antora --stacktrace --cache-dir cache --redirect-facility static --clean --fetch site.yml --attribute format=html
[14:03:47.030] FATAL (antora): Cannot find module 'b4a'
```

Restarting CI to see if it is a hard fail.

**Comment by mmattel** [comment]
This is strange because `b4a@^1.6.4` is present in the lock file???
There is also no change compared to the docs PR??
Could it be that there is an issue internally running `yarn install` ??

**Comment by phil-davis** [comment]
Are there any other dependency PRs that still need to be back-ported? With later versions of yarn/antora or some component that these use to build?

**Comment by mmattel** [comment]
No, nothing else is open.
I am wordering why `b4a` is in the `yarn.lock` file, but seems not to be installed during the process.
The lock files are the same in all repos and branches.

But I could do one thing. Taking the backport, I could give it a try to not backport the lock file but let it recreate. I will file a commit for this PR.

**Comment by phil-davis** [comment]
That worked.

**Comment by mmattel** [comment]
ok, the PR is now green.

**LEARNING:**
Backporting a lockfile is not a good idea.
You need to recreate the lockfile without the modules changed with yarn install and then add the modules back and install again. The lockfile is then clean and can be pushed. I will file a doc note in the docs repo.

**Pull request merged**
